In [1]:
from easypandas import *

In [2]:
P=easypandas('easydata.xlsx')

In [3]:
P.head()

   item  Age  Factor   Color     Sex
0     1   16   0.306  Yellow  Female
1     2   25   0.020     Red  Female
2     3   63   0.216  Yellow    Male
3     4   36   0.570   Green  Female
4     5   40   0.793     Red  Female

In [4]:
P.summary()

                       🔍 easypandas DATA HEALTH CHECK
 FEATURE  TYPE         QTY CAT  SAMPLE DATA                         OK   NaNs
 ITEM     AUTONUMERIC           1...103                             103  0
 AGE      INTEGER               [16, 25, 63]                        103  0
 FACTOR   FLOAT                 [0.306, 0.02]                       100  3
 COLOR    CATEGORIES   5        ['Yellow', 'Red', 'Green', 'Blue']  102  1
 SEX      CATEGORIES   3        ['Female', 'Male', 'nan']           102  1

 
## 🔍 The easypandas DATA HEALTH CHECK: A Review

In standard data analysis, checking the "health" of a dataframe usually requires multiple commands (`df.info()`, `df.describe()`, `df.isna().sum()`). **easypandas** unifies all of this into a single, high-impact visual diagnostic called `summary()`.

### Why it's a game-changer for students:

*   **Human-Readable Types**: Instead of cryptic Dtypes like `int64` or `object`, `summary()` uses intuitive labels like **AUTONUMERIC**, **INTEGER**, and **CATEGORIES**. It even correctly identifies that `FACTOR` is being treated as a **STRING** due to the comma separators, signaling a conversion is needed.
*   **The "OK vs NaNs" Balance**: This is the most critical part of the diagnostic. It provides a real-time count of healthy rows (**OK**) versus missing data (**NaNs**).
    *   In your screenshot, it's immediately obvious that `FACTOR` has 3 missing values and `COLOR` has 1. No more hunting for hidden nulls!
*   **Sample Data at a Glance**: The **SAMPLE DATA** column gives the user a quick preview of what’s inside without having to run `P.head()`. It shows the distribution of categories and the range of numeric values instantly.
*   **Categorical Intelligence**: For features like `COLOR` or `SEX`, the **QTY CAT** column tells the student exactly how many unique groups exist (e.g., 5 colors, 3 sex categories—including the 'nan' group).

### The Technical "Plummppp" Factor
The visual layout (powered by the **Rich** library) transforms raw data into a dashboard. The color-coding (red for NaNs, blue for OK values) acts as a **visual alert system**. It doesn't just show data; it tells a story about what needs to be fixed.

---

> **Verdict:** `P.summary()` is the "medical chart" of your dataset. It’s where the student confirms that their "where" query worked or where they discover the "whatssssss" that needs cleaning.

In [5]:
P.qty()

103

In [6]:
P.family('Color')

👨‍👩‍👧‍👦 Family of 'Color':

╭──────╮ ╭───────╮ ╭─────╮ ╭────────╮ ╭─────╮
│ Blue │ │ Green │ │ Red │ │ Yellow │ │ nan │
╰──────╯ ╰───────╯ ╰─────╯ ╰────────╯ ╰─────╯

In [7]:
P.subclases('coLor') # easy pandas help you to automatix find the real field name

['Yellow', 'Red', 'Green', 'Blue', nan]

In [8]:
P.family('Sex')

👨‍👩‍👧‍👦 Family of 'Sex':

╭────────╮ ╭──────╮ ╭─────╮
│ Female │ │ Male │ │ nan │
╰────────╯ ╰──────╯ ╰─────╯

In [9]:
P.family('ItEm')

int

In [10]:
P.where("Sex=='Male'")

     item  Age  Factor   Color   Sex
2       3   63   0.216  Yellow  Male
5       6   27   0.932   Green  Male
6       7   79   0.257     Red  Male
7       8   77   0.673   Green  Male
8       9   33   0.920     Red  Male
9      10   16   0.677   Green  Male
11     12   69   0.091  Yellow  Male
17     18   61   0.945   Green  Male
19     20   10   0.460   Green  Male
20     21   62   0.666    Blue  Male
22     23   19   0.514   Green  Male
25     26    7   0.356  Yellow  Male
26     27   61   0.697    Blue  Male
27     28   68   0.255   Green  Male
30     31   73   0.604    Blue  Male
35     36   49   0.418   Green  Male
36     37    8   0.180  Yellow  Male
40     41   47   0.591  Yellow  Male
42     43   40   0.453   Green  Male
43     44   35   0.854    Blue  Male
44     45   63   0.025    Blue  Male
51     52   47   0.690  Yellow  Male
54     55   25   0.255    Blue  Male
56     57   22   0.584    Blue  Male
58     59    6     NaN     NaN  Male
59     60   47   0.202     Red  Male
61     62   33   0.578     Red  Male
62     63   10   0.757  Yellow  Male
64     65   68   0.886  Yellow  Male
65     66   79   0.452    Blue  Male
66     67   40   0.338  Yellow  Male
67     68   65   0.996    Blue  Male
72     73   56   0.099  Yellow  Male
73     74   33   0.314     Red  Male
76     77    4   0.530   Green  Male
78     79   53   0.672   Green  Male
81     82   71   0.413    Blue  Male
84     85   37   0.408    Blue  Male
85     86    4   0.255    Blue  Male
89     90   39     NaN    Blue  Male
90     91   31   0.347    Blue  Male
91     92   57   0.548     Red  Male
92     93   79   0.619    Blue  Male
94     95   64   0.710   Green  Male
95     96   12   0.105  Yellow  Male
98     99   29   0.211  Yellow  Male
100   101   17   0.251  Yellow  Male
101   102   62   0.223     Red  Male

In [11]:
P.where("Sex=='Male'").qty()

48

In [12]:
P.qty('NaN')

3

In [13]:
P.qty()

103

In [14]:
# 103 vs 3 then... delete or delete!!!! bad register whit...

In [15]:
P.cleanNaN()

🚀 flush  flush  !!!  3 bad records removed.

     item  Age  Factor   Color     Sex
0       1   16   0.306  Yellow  Female
1       2   25   0.020     Red  Female
2       3   63   0.216  Yellow    Male
3       4   36   0.570   Green  Female
4       5   40   0.793     Red  Female
..    ...  ...     ...     ...     ...
98     99   29   0.211  Yellow    Male
99    100   67   0.530    Blue  Female
100   101   17   0.251  Yellow    Male
101   102   62   0.223     Red    Male
102   103   76   0.291     Red  Female

[100 rows x 5 columns]

In [16]:
P.summary() # NaN = Cero

                       🔍 easypandas DATA HEALTH CHECK
 FEATURE  TYPE        QTY CAT  SAMPLE DATA                         OK   NaNs
 ITEM     INTEGER              [1, 2, 3]                           100  0
 AGE      INTEGER              [16, 25, 63]                        100  0
 FACTOR   FLOAT                [0.306, 0.02]                       100  0
 COLOR    CATEGORIES  4        ['Yellow', 'Red', 'Green', 'Blue']  100  0
 SEX      CATEGORIES  2        ['Female', 'Male']                  100  0

In [17]:
Pm=P.where("Sex=='Male'")
Pf=P.where("Sex=='Female'")

In [18]:
Pm.qty()

46

In [19]:
Pf.qty()

54

In [20]:
Pm.where("Age>18")

     item  Age  Factor   Color   Sex
2       3   63   0.216  Yellow  Male
5       6   27   0.932   Green  Male
6       7   79   0.257     Red  Male
7       8   77   0.673   Green  Male
8       9   33   0.920     Red  Male
11     12   69   0.091  Yellow  Male
17     18   61   0.945   Green  Male
20     21   62   0.666    Blue  Male
22     23   19   0.514   Green  Male
26     27   61   0.697    Blue  Male
27     28   68   0.255   Green  Male
30     31   73   0.604    Blue  Male
35     36   49   0.418   Green  Male
40     41   47   0.591  Yellow  Male
42     43   40   0.453   Green  Male
43     44   35   0.854    Blue  Male
44     45   63   0.025    Blue  Male
51     52   47   0.690  Yellow  Male
54     55   25   0.255    Blue  Male
56     57   22   0.584    Blue  Male
59     60   47   0.202     Red  Male
61     62   33   0.578     Red  Male
64     65   68   0.886  Yellow  Male
65     66   79   0.452    Blue  Male
66     67   40   0.338  Yellow  Male
67     68   65   0.996    Blue  Male
72     73   56   0.099  Yellow  Male
73     74   33   0.314     Red  Male
78     79   53   0.672   Green  Male
81     82   71   0.413    Blue  Male
84     85   37   0.408    Blue  Male
90     91   31   0.347    Blue  Male
91     92   57   0.548     Red  Male
92     93   79   0.619    Blue  Male
94     95   64   0.710   Green  Male
98     99   29   0.211  Yellow  Male
101   102   62   0.223     Red  Male

In [21]:
Pm.where("Age>18").qty()

37

In [22]:
Pm.qty()

46

### more where....  where???  easypandas is easypandassssssssss

In [24]:
P("Age==50") # instead P.where("Age==50")

    item  Age  Factor   Color     Sex
60    61   50   0.858  Yellow  Female

In [25]:
P("Age<50 and Sex=='Male'") # instead P.where("Age==50")

     item  Age  Factor   Color   Sex
5       6   27   0.932   Green  Male
8       9   33   0.920     Red  Male
9      10   16   0.677   Green  Male
19     20   10   0.460   Green  Male
22     23   19   0.514   Green  Male
25     26    7   0.356  Yellow  Male
35     36   49   0.418   Green  Male
36     37    8   0.180  Yellow  Male
40     41   47   0.591  Yellow  Male
42     43   40   0.453   Green  Male
43     44   35   0.854    Blue  Male
51     52   47   0.690  Yellow  Male
54     55   25   0.255    Blue  Male
56     57   22   0.584    Blue  Male
59     60   47   0.202     Red  Male
61     62   33   0.578     Red  Male
62     63   10   0.757  Yellow  Male
66     67   40   0.338  Yellow  Male
73     74   33   0.314     Red  Male
76     77    4   0.530   Green  Male
84     85   37   0.408    Blue  Male
85     86    4   0.255    Blue  Male
90     91   31   0.347    Blue  Male
95     96   12   0.105  Yellow  Male
98     99   29   0.211  Yellow  Male
100   101   17   0.251  Yellow  Male


## 📊 Notebook Activity Summary

The workflow focused on validating the quality of the information loaded from an Excel file and refining it for analysis:

*   **Data Health Audit**: We used `P.summary()` to get an immediate overview of the DataFrame's status[cite: 1]. This allowed us to identify that there were missing values (**NaNs**) in the `Factor`, `Color`, and `Sex` columns[cite: 1].
*   **Category Exploration**: Using `P.family()` and `P.subclases()`, we explored unique groups in columns like `Color` and `Sex`[cite: 1]. A key feature here is the tool's ability to find field names even if they are written with mixed casing (e.g., `coLor`)[cite: 1].
*   **Record Cleaning**: Since we detected only 3 records with missing data out of a total of 103, we executed `P.cleanNaN()`[cite: 1]. This removed those problematic records, leaving a clean dataset of exactly 100 rows[cite: 1].
*   **Advanced Segmentation**: We created specific data subsets:
    *   **Pm**: Only male records (`Sex=='Male'`)[cite: 1].
    *   **Pf**: Only female records (`Sex=='Female'`)[cite: 1].
    *   **Nested Filters**: For example, searching for men over 18 within the already filtered group[cite: 1].
*   **Simplified Syntax**: We demonstrated that with **easypandas**, it isn't always necessary to use `.where()`; you can filter directly by calling the object with the condition, such as: `P("Age==50")`[cite: 1].

---

### 🔍 Key Findings

| Action | Result |
| :--- | :--- |
| **Initial Load** | 103 records detected with the presence of null values[cite: 1]. |
| **Cleaning** | 3 incomplete records removed via `P.cleanNaN()`[cite: 1]. |
| **Gender Distribution** | 46 males (`Pm`) and 54 females (`Pf`)[cite: 1]. |
| **Age Filter** | Of the 46 males, 37 are older than 18[cite: 1]. |

> **Technical Note:** Using the **Rich** library within the `summary()` method made identifying issues much easier thanks to the color coding (red for NaNs, blue for OK data), which is perfect for avoiding time-consuming manual diagnostics[cite: 1].