# easypandas — Simple Data Exploration for Students

`easypandas` is a small educational wrapper around **pandas** that provides a simpler interface for beginners learning data analysis.

The goal is to allow students to explore datasets using simple and intuitive commands.

Internally it uses the power of **pandas**, but exposes a friendlier syntax.

---

# Creating a Dataset

Example dataset:

In [1]:
from  lib_pandas import *

data = {
"nombre":["Ana","Luis","Pedro"],
"edad":[30,40,36],
"qty_autos":[1,2,0]
}

P = easypandas(data)

# Basic Exploration

## Number of rows

In [2]:
P.qty

3

## Show first rows

In [3]:
P.show()

  nombre  edad  qty_autos
0    Ana    30          1
1   Luis    40          2
2  Pedro    36          0

## Show last rows

In [4]:
P.end()

  nombre  edad  qty_autos
0    Ana    30          1
1   Luis    40          2
2  Pedro    36          0

## List columns

In [5]:
P.fields()

['nombre', 'edad', 'qty_autos']

# Filtering Data

You can filter rows using simple expressions.

In [6]:
P.where("edad > 30")

  nombre  edad  qty_autos
1   Luis    40          2
2  Pedro    36          0

nombre   edad   qty_autos
Luis     40     2
Pedro    36     0
```

This follows the logical expression:

$$
edad > 30
$$

In [7]:
P.mean()

(['edad', 'qty_autos'], [np.float64(35.333333333333336), np.float64(1.0)])

Mathematically the mean is defined as

$$
\bar{x} = \frac{1}{n}\sum_{i=1}^{n} x_i
$$
## Mean of a specific column

In [8]:
P.mean("edad")

35.333333333333336

# Counting Values

In [9]:
P.count("nombre")

{'Ana': 1, 'Luis': 1, 'Pedro': 1}

# Unique Values

In [10]:
P.unique("nombre")

['Ana', 'Luis', 'Pedro']

# Most Frequent Values

In [11]:
P.top("nombre")

nombre
Ana      1
Luis     1
Pedro    1
Name: count, dtype: int64

This returns the most common values in a column.

---

# Index Management

## Set a column as index

In [12]:
P.setindex("nombre")

## Reset index

In [13]:
P.resetindex()

# Dataset Summary

In [14]:
P.summary()

rows: 3
fields: 3

nombre  text  unique: 3
edad  numeric  mean: 35.33
qty_autos  numeric  mean: 1.0

# Mathematical Interpretation

For numeric columns, statistics are computed using common formulas.

Mean:

$$
\bar{x} = \frac{x_1 + x_2 + ... + x_n}{n}
$$

Variance:

$$
\sigma^2 = \frac{1}{n}\sum (x_i - \bar{x})^2
$$

Standard deviation:

$$
\sigma = \sqrt{\sigma^2}
$$

---

# Typical Workflow

A typical student exploration session might look like:

In [15]:
P.summary()

rows: 3
fields: 3

nombre  text  unique: 3
edad  numeric  mean: 35.33
qty_autos  numeric  mean: 1.0

In [16]:
P.show()

  nombre  edad  qty_autos
0    Ana    30          1
1   Luis    40          2
2  Pedro    36          0

In [17]:
P.mean("edad")

35.333333333333336

In [18]:
P.count("nombre")

{'Ana': 1, 'Luis': 1, 'Pedro': 1}

In [19]:
P.where("edad > 30")

  nombre  edad  qty_autos
1   Luis    40          2
2  Pedro    36          0

# Philosophy

The philosophy of `easypandas` is:

* Simplicity
* Readability
* Learning before complexity

Students first explore data using simple commands, and later transition to full **pandas** functionality.